#!/bin/sh
ACCESSKEY=$SIGSCI_ACCESSKEY
SECRETKEY=$SIGSCI_SECRETKEY
RPCADDRESS=$SIGSCI_RPCADDRESS
DOCKERID=`hostname`
INSTHOST="$SIGSCI_HOSTNAME-$DOCKERID"
export SIGSCI_SERVER_HOSTNAME=$INSTHOST


/usr/sbin/nginx &
/usr/sbin/sigsci-agent
